//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int ID { get; set; }
        public bool IsActive { get; set; }
        public int CustomerID { get; set; }
        public string ContactItemType { get; set; }
        public string ContactItemValue { get; set; }
    }
}
