//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public System.DateTime INSERT_TIMESTAMP { get; set; }
        public string INSERT_USER { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public string CustomerType { get; set; }
        public string CustomerName { get; set; }
        public string Personal_Gender { get; set; }
        public Nullable<System.DateTime> Personal_BirthDate { get; set; }
        public string Personal_SSN { get; set; }
        public string Personal_LicenseID { get; set; }
        public string Business_TypeOfCompany { get; set; }
        public string Business_TaxID { get; set; }
        public string Notes { get; set; }
    }
}
