<?xml version="1.0" encoding="utf-8"?><Database Name="PM" Class="PMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLExpress;Initial Catalog=PM;Integrated Security=True" SettingsObjectName="PM.Properties.Settings" SettingsPropertyName="PMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customer">
    <Type Name="Customer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="INSERT_TIMESTAMP" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="INSERT_USER" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OpeningDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CustomerType" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Personal_Gender" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Personal_BirthDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Personal_SSN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Personal_LicenseID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Business_TypeOfCompany" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Business_TaxID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lookups" Member="Lookups">
    <Type Name="Lookup">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LookupType" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LookupName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Contacts" Member="Contacts">
    <Type Name="Contact">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="INSERT_TIMESTAMP" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="INSERT_USER" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContactItemType" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ContactItemValue" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DocumentFolders" Member="DocumentFolders">
    <Type Name="DocumentFolder">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="INSERT_TIMESTAMP" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="INSERT_USER" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FolderName" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="IsStarred" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsHidden" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DocumentData" Member="DocumentDatas">
    <Type Name="DocumentData">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="INSERT_TIMESTAMP" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="INSERT_USER" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DocumentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RawData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.EventLog" Member="EventLog">
    <Type Name="EventLog">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LOG_TIMESTAMP" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LOG_USER" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EventType" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EventMessage" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Documents" Member="Documents">
    <Type Name="Document">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="INSERT_TIMESTAMP" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="INSERT_USER" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DocumentFolderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocumentFileName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DocumentType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FileType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FileTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UploadDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpirationDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DocumentActivityLog" Member="DocumentActivityLogs">
    <Type Name="DocumentActivityLog">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LOG_TIMESTAMP" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LOG_USER" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EventType" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DocumentFileName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="FolderName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RelatedParties" Member="RelatedParties">
    <Type Name="RelatedParties">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="INSERT_TIMESTAMP" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="INSERT_USER" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PartyName" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="EntityType" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SSN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LicenseID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_CreateDefaultDocumentFolders" Method="sp_CreateDefaultDocumentFolders">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fn_GetDocumentFolderCountForCustomer" Method="fn_GetDocumentFolderCountForCustomer" IsComposable="true">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DeleteDocumentFolder" Method="sp_DeleteDocumentFolder">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fn_GetDocumentFoldersForCustomer" Method="fn_GetDocumentFoldersForCustomer" IsComposable="true">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <ElementType Name="fn_GetDocumentFoldersForCustomerResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="INSERT_TIMESTAMP" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="INSERT_USER" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FolderName" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="IsStarred" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsHidden" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_DeleteDocument" Method="sp_DeleteDocument">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_SaveDocumentData" Method="sp_SaveDocumentData">
    <Parameter Name="DocumentID" Parameter="documentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RawData" Parameter="rawData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_SaveDocumentFolder" Method="sp_SaveDocumentFolder">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ParentID" Parameter="parentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FolderName" Parameter="folderName" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="IsStarred" Parameter="isStarred" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsHidden" Parameter="isHidden" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UploadDocumentData" Method="sp_UploadDocumentData">
    <Parameter Name="DocumentID" Parameter="documentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FileName" Parameter="fileName" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fn_GetRawDocumentData" Method="fn_GetRawDocumentData" IsComposable="true">
    <Parameter Name="DocumentID" Parameter="documentID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Data.Linq.Binary" />
  </Function>
  <Function Name="dbo.fn_GetAllFolderNames" Method="fn_GetAllFolderNames" IsComposable="true">
    <Parameter Name="ActiveOnly" Parameter="activeOnly" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="fn_GetAllFolderNamesResult">
      <Column Name="FolderName" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SyncDocumentType" Method="sp_SyncDocumentType">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AddEventLog" Method="sp_AddEventLog">
    <Parameter Name="EventType" Parameter="eventType" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="EventMessage" Parameter="eventMessage" Type="System.String" DbType="NVarChar(1000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fn_GetDocumentsForCustomer" Method="fn_GetDocumentsForCustomer" IsComposable="true">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ActiveOnly" Parameter="activeOnly" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="fn_GetDocumentsForCustomerResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DocumentFolderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocumentFileName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DocumentType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FileType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FileTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UploadDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpirationDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SaveDocument" Method="sp_SaveDocument">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DocumentFolderID" Parameter="documentFolderID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DocumentFileName" Parameter="documentFileName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="DocumentType" Parameter="documentType" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="FileType" Parameter="fileType" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="FileTimestamp" Parameter="fileTimestamp" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UploadDate" Parameter="uploadDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ExpirationDate" Parameter="expirationDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Comments" Parameter="comments" Type="System.String" DbType="NVarChar(1000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AddDocumentActivityLog" Method="sp_AddDocumentActivityLog">
    <Parameter Name="EventType" Parameter="eventType" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="CustomerName" Parameter="customerName" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="DocumentFileName" Parameter="documentFileName" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="FolderName" Parameter="folderName" Type="System.String" DbType="NVarChar(1000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fn_GetDocumentFolderTree" Method="fn_GetDocumentFolderTree" IsComposable="true">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <ElementType Name="fn_GetDocumentFolderTreeResult">
      <Column Name="DocumentFolderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentDocumentFolderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="FolderName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsHidden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsStarred" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FolderTree" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="BranchLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.fn_GetFolderTreeForDocumentFolderID" Method="fn_GetFolderTreeForDocumentFolderID" IsComposable="true">
    <Parameter Name="DocumentFolderID" Parameter="documentFolderID" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.fn_GetDocumentsForFilter" Method="fn_GetDocumentsForFilter" IsComposable="true">
    <ElementType Name="fn_GetDocumentsForFilterResult">
      <Column Name="DocumentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DocumentFolderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDocumentDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DocumentFileName" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="FileType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DocumentType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FileTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UploadDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpirationDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsCustomerActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FolderName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="FolderTree" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsFolderHidden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsFolderBookmarked" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SaveCustomer" Method="sp_SaveCustomer">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="OpeningDate" Parameter="openingDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="CustomerType" Parameter="customerType" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="CustomerName" Parameter="customerName" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="Personal_Gender" Parameter="personal_Gender" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Personal_BirthDate" Parameter="personal_BirthDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Personal_SSN" Parameter="personal_SSN" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Personal_LicenseID" Parameter="personal_LicenseID" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Business_TypeOfCompany" Parameter="business_TypeOfCompany" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Business_TaxID" Parameter="business_TaxID" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="NVarChar(4000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fn_CustomerNameExists" Method="fn_CustomerNameExists" IsComposable="true">
    <Parameter Name="CustomerName" Parameter="customerName" Type="System.String" DbType="NVarChar(1000)" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.sp_SaveContact" Method="sp_SaveContact">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ContactItemType" Parameter="contactItemType" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ContactItemValue" Parameter="contactItemValue" Type="System.String" DbType="NVarChar(1000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_SaveRelatedParty" Method="sp_SaveRelatedParty">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PartyName" Parameter="partyName" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="EntityType" Parameter="entityType" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="BirthDate" Parameter="birthDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="SSN" Parameter="sSN" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="LicenseID" Parameter="licenseID" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="NVarChar(4000)" />
    <Return Type="System.Int32" />
  </Function>
</Database>