#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PM")]
	public partial class PMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void InsertLookup(Lookup instance);
    partial void UpdateLookup(Lookup instance);
    partial void DeleteLookup(Lookup instance);
    partial void InsertContact(Contact instance);
    partial void UpdateContact(Contact instance);
    partial void DeleteContact(Contact instance);
    partial void InsertDocumentFolder(DocumentFolder instance);
    partial void UpdateDocumentFolder(DocumentFolder instance);
    partial void DeleteDocumentFolder(DocumentFolder instance);
    partial void InsertDocumentData(DocumentData instance);
    partial void UpdateDocumentData(DocumentData instance);
    partial void DeleteDocumentData(DocumentData instance);
    partial void InsertEventLog(EventLog instance);
    partial void UpdateEventLog(EventLog instance);
    partial void DeleteEventLog(EventLog instance);
    partial void InsertDocument(Document instance);
    partial void UpdateDocument(Document instance);
    partial void DeleteDocument(Document instance);
    partial void InsertDocumentActivityLog(DocumentActivityLog instance);
    partial void UpdateDocumentActivityLog(DocumentActivityLog instance);
    partial void DeleteDocumentActivityLog(DocumentActivityLog instance);
    #endregion
		
		public PMDataContext() : 
				base(global::PM.Properties.Settings.Default.PMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer> Customer
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<Lookup> Lookups
		{
			get
			{
				return this.GetTable<Lookup>();
			}
		}
		
		public System.Data.Linq.Table<Contact> Contacts
		{
			get
			{
				return this.GetTable<Contact>();
			}
		}
		
		public System.Data.Linq.Table<DocumentFolder> DocumentFolders
		{
			get
			{
				return this.GetTable<DocumentFolder>();
			}
		}
		
		public System.Data.Linq.Table<DocumentData> DocumentDatas
		{
			get
			{
				return this.GetTable<DocumentData>();
			}
		}
		
		public System.Data.Linq.Table<EventLog> EventLog
		{
			get
			{
				return this.GetTable<EventLog>();
			}
		}
		
		public System.Data.Linq.Table<Document> Documents
		{
			get
			{
				return this.GetTable<Document>();
			}
		}
		
		public System.Data.Linq.Table<DocumentActivityLog> DocumentActivityLogs
		{
			get
			{
				return this.GetTable<DocumentActivityLog>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CreateDefaultDocumentFolders")]
		public int sp_CreateDefaultDocumentFolders([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_GetDocumentFolderCountForCustomer", IsComposable=true)]
		public System.Nullable<int> fn_GetDocumentFolderCountForCustomer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DeleteDocumentFolder")]
		public int sp_DeleteDocumentFolder([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_GetDocumentFoldersForCustomer", IsComposable=true)]
		public IQueryable<fn_GetDocumentFoldersForCustomerResult> fn_GetDocumentFoldersForCustomer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID)
		{
			return this.CreateMethodCallQuery<fn_GetDocumentFoldersForCustomerResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DeleteDocument")]
		public int sp_DeleteDocument([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SaveDocumentData")]
		public int sp_SaveDocumentData([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentID", DbType="Int")] System.Nullable<int> documentID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RawData", DbType="VarBinary(MAX)")] System.Data.Linq.Binary rawData)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documentID, rawData);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SaveDocumentFolder")]
		public int sp_SaveDocumentFolder([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentID", DbType="Int")] System.Nullable<int> parentID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FolderName", DbType="NVarChar(1000)")] string folderName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsStarred", DbType="Bit")] System.Nullable<bool> isStarred, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsHidden", DbType="Bit")] System.Nullable<bool> isHidden)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, customerID, parentID, folderName, isStarred, isHidden);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UploadDocumentData")]
		public int sp_UploadDocumentData([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentID", DbType="Int")] System.Nullable<int> documentID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileName", DbType="NVarChar(255)")] string fileName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documentID, fileName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_GetRawDocumentData", IsComposable=true)]
		public System.Data.Linq.Binary fn_GetRawDocumentData([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentID", DbType="Int")] System.Nullable<int> documentID)
		{
			return ((System.Data.Linq.Binary)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documentID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_GetAllFolderNames", IsComposable=true)]
		public IQueryable<fn_GetAllFolderNamesResult> fn_GetAllFolderNames([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ActiveOnly", DbType="Bit")] System.Nullable<bool> activeOnly)
		{
			return this.CreateMethodCallQuery<fn_GetAllFolderNamesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), activeOnly);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SyncDocumentType")]
		public int sp_SyncDocumentType()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_AddEventLog")]
		public int sp_AddEventLog([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EventType", DbType="NVarChar(100)")] string eventType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EventMessage", DbType="NVarChar(1000)")] string eventMessage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eventType, eventMessage);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_GetDocumentsForCustomer", IsComposable=true)]
		public IQueryable<fn_GetDocumentsForCustomerResult> fn_GetDocumentsForCustomer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ActiveOnly", DbType="Bit")] System.Nullable<bool> activeOnly)
		{
			return this.CreateMethodCallQuery<fn_GetDocumentsForCustomerResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerID, activeOnly);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SaveDocument")]
		public int sp_SaveDocument([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentFolderID", DbType="Int")] System.Nullable<int> documentFolderID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentFileName", DbType="NVarChar(100)")] string documentFileName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentType", DbType="NVarChar(100)")] string documentType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileType", DbType="NVarChar(100)")] string fileType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileTimestamp", DbType="DateTime")] System.Nullable<System.DateTime> fileTimestamp, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UploadDate", DbType="Date")] System.Nullable<System.DateTime> uploadDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpirationDate", DbType="Date")] System.Nullable<System.DateTime> expirationDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comments", DbType="NVarChar(1000)")] string comments)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, customerID, documentFolderID, documentFileName, documentType, fileType, fileTimestamp, uploadDate, expirationDate, comments);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_AddDocumentActivityLog")]
		public int sp_AddDocumentActivityLog([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EventType", DbType="NVarChar(100)")] string eventType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerName", DbType="NVarChar(1000)")] string customerName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentFileName", DbType="NVarChar(1000)")] string documentFileName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FolderName", DbType="NVarChar(1000)")] string folderName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eventType, customerName, documentFileName, folderName);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _INSERT_TIMESTAMP;
		
		private string _INSERT_USER;
		
		private bool _IsActive;
		
		private System.Nullable<System.DateTime> _OpeningDate;
		
		private string _CustomerType;
		
		private string _CustomerName;
		
		private string _Personal_Gender;
		
		private System.Nullable<System.DateTime> _Personal_BirthDate;
		
		private string _Personal_SSN;
		
		private string _Personal_LicenseID;
		
		private string _Business_TypeOfCompany;
		
		private string _Business_TaxID;
		
		private string _Notes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnINSERT_TIMESTAMPChanging(System.DateTime value);
    partial void OnINSERT_TIMESTAMPChanged();
    partial void OnINSERT_USERChanging(string value);
    partial void OnINSERT_USERChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnOpeningDateChanging(System.Nullable<System.DateTime> value);
    partial void OnOpeningDateChanged();
    partial void OnCustomerTypeChanging(string value);
    partial void OnCustomerTypeChanged();
    partial void OnCustomerNameChanging(string value);
    partial void OnCustomerNameChanged();
    partial void OnPersonal_GenderChanging(string value);
    partial void OnPersonal_GenderChanged();
    partial void OnPersonal_BirthDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPersonal_BirthDateChanged();
    partial void OnPersonal_SSNChanging(string value);
    partial void OnPersonal_SSNChanged();
    partial void OnPersonal_LicenseIDChanging(string value);
    partial void OnPersonal_LicenseIDChanged();
    partial void OnBusiness_TypeOfCompanyChanging(string value);
    partial void OnBusiness_TypeOfCompanyChanged();
    partial void OnBusiness_TaxIDChanging(string value);
    partial void OnBusiness_TaxIDChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    #endregion
		
		public Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSERT_TIMESTAMP", DbType="DateTime NOT NULL")]
		public System.DateTime INSERT_TIMESTAMP
		{
			get
			{
				return this._INSERT_TIMESTAMP;
			}
			set
			{
				if ((this._INSERT_TIMESTAMP != value))
				{
					this.OnINSERT_TIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._INSERT_TIMESTAMP = value;
					this.SendPropertyChanged("INSERT_TIMESTAMP");
					this.OnINSERT_TIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSERT_USER", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string INSERT_USER
		{
			get
			{
				return this._INSERT_USER;
			}
			set
			{
				if ((this._INSERT_USER != value))
				{
					this.OnINSERT_USERChanging(value);
					this.SendPropertyChanging();
					this._INSERT_USER = value;
					this.SendPropertyChanged("INSERT_USER");
					this.OnINSERT_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpeningDate", DbType="Date")]
		public System.Nullable<System.DateTime> OpeningDate
		{
			get
			{
				return this._OpeningDate;
			}
			set
			{
				if ((this._OpeningDate != value))
				{
					this.OnOpeningDateChanging(value);
					this.SendPropertyChanging();
					this._OpeningDate = value;
					this.SendPropertyChanged("OpeningDate");
					this.OnOpeningDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerType", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CustomerType
		{
			get
			{
				return this._CustomerType;
			}
			set
			{
				if ((this._CustomerType != value))
				{
					this.OnCustomerTypeChanging(value);
					this.SendPropertyChanging();
					this._CustomerType = value;
					this.SendPropertyChanged("CustomerType");
					this.OnCustomerTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this.OnCustomerNameChanging(value);
					this.SendPropertyChanging();
					this._CustomerName = value;
					this.SendPropertyChanged("CustomerName");
					this.OnCustomerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Personal_Gender", DbType="NVarChar(100)")]
		public string Personal_Gender
		{
			get
			{
				return this._Personal_Gender;
			}
			set
			{
				if ((this._Personal_Gender != value))
				{
					this.OnPersonal_GenderChanging(value);
					this.SendPropertyChanging();
					this._Personal_Gender = value;
					this.SendPropertyChanged("Personal_Gender");
					this.OnPersonal_GenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Personal_BirthDate", DbType="Date")]
		public System.Nullable<System.DateTime> Personal_BirthDate
		{
			get
			{
				return this._Personal_BirthDate;
			}
			set
			{
				if ((this._Personal_BirthDate != value))
				{
					this.OnPersonal_BirthDateChanging(value);
					this.SendPropertyChanging();
					this._Personal_BirthDate = value;
					this.SendPropertyChanged("Personal_BirthDate");
					this.OnPersonal_BirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Personal_SSN", DbType="NVarChar(100)")]
		public string Personal_SSN
		{
			get
			{
				return this._Personal_SSN;
			}
			set
			{
				if ((this._Personal_SSN != value))
				{
					this.OnPersonal_SSNChanging(value);
					this.SendPropertyChanging();
					this._Personal_SSN = value;
					this.SendPropertyChanged("Personal_SSN");
					this.OnPersonal_SSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Personal_LicenseID", DbType="NVarChar(100)")]
		public string Personal_LicenseID
		{
			get
			{
				return this._Personal_LicenseID;
			}
			set
			{
				if ((this._Personal_LicenseID != value))
				{
					this.OnPersonal_LicenseIDChanging(value);
					this.SendPropertyChanging();
					this._Personal_LicenseID = value;
					this.SendPropertyChanged("Personal_LicenseID");
					this.OnPersonal_LicenseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Business_TypeOfCompany", DbType="NVarChar(100)")]
		public string Business_TypeOfCompany
		{
			get
			{
				return this._Business_TypeOfCompany;
			}
			set
			{
				if ((this._Business_TypeOfCompany != value))
				{
					this.OnBusiness_TypeOfCompanyChanging(value);
					this.SendPropertyChanging();
					this._Business_TypeOfCompany = value;
					this.SendPropertyChanged("Business_TypeOfCompany");
					this.OnBusiness_TypeOfCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Business_TaxID", DbType="NVarChar(100)")]
		public string Business_TaxID
		{
			get
			{
				return this._Business_TaxID;
			}
			set
			{
				if ((this._Business_TaxID != value))
				{
					this.OnBusiness_TaxIDChanging(value);
					this.SendPropertyChanging();
					this._Business_TaxID = value;
					this.SendPropertyChanged("Business_TaxID");
					this.OnBusiness_TaxIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(4000)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lookups")]
	public partial class Lookup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _LookupType;
		
		private int _SortOrder;
		
		private string _LookupName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLookupTypeChanging(string value);
    partial void OnLookupTypeChanged();
    partial void OnSortOrderChanging(int value);
    partial void OnSortOrderChanged();
    partial void OnLookupNameChanging(string value);
    partial void OnLookupNameChanged();
    #endregion
		
		public Lookup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LookupType", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string LookupType
		{
			get
			{
				return this._LookupType;
			}
			set
			{
				if ((this._LookupType != value))
				{
					this.OnLookupTypeChanging(value);
					this.SendPropertyChanging();
					this._LookupType = value;
					this.SendPropertyChanged("LookupType");
					this.OnLookupTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int NOT NULL")]
		public int SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LookupName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string LookupName
		{
			get
			{
				return this._LookupName;
			}
			set
			{
				if ((this._LookupName != value))
				{
					this.OnLookupNameChanging(value);
					this.SendPropertyChanging();
					this._LookupName = value;
					this.SendPropertyChanged("LookupName");
					this.OnLookupNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contacts")]
	public partial class Contact : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _INSERT_TIMESTAMP;
		
		private string _INSERT_USER;
		
		private bool _IsActive;
		
		private int _CustomerID;
		
		private string _ContactItemType;
		
		private string _ContactItemValue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnINSERT_TIMESTAMPChanging(System.DateTime value);
    partial void OnINSERT_TIMESTAMPChanged();
    partial void OnINSERT_USERChanging(string value);
    partial void OnINSERT_USERChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnCustomerIDChanging(int value);
    partial void OnCustomerIDChanged();
    partial void OnContactItemTypeChanging(string value);
    partial void OnContactItemTypeChanged();
    partial void OnContactItemValueChanging(string value);
    partial void OnContactItemValueChanged();
    #endregion
		
		public Contact()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSERT_TIMESTAMP", DbType="DateTime NOT NULL")]
		public System.DateTime INSERT_TIMESTAMP
		{
			get
			{
				return this._INSERT_TIMESTAMP;
			}
			set
			{
				if ((this._INSERT_TIMESTAMP != value))
				{
					this.OnINSERT_TIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._INSERT_TIMESTAMP = value;
					this.SendPropertyChanged("INSERT_TIMESTAMP");
					this.OnINSERT_TIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSERT_USER", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string INSERT_USER
		{
			get
			{
				return this._INSERT_USER;
			}
			set
			{
				if ((this._INSERT_USER != value))
				{
					this.OnINSERT_USERChanging(value);
					this.SendPropertyChanging();
					this._INSERT_USER = value;
					this.SendPropertyChanged("INSERT_USER");
					this.OnINSERT_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int NOT NULL")]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactItemType", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ContactItemType
		{
			get
			{
				return this._ContactItemType;
			}
			set
			{
				if ((this._ContactItemType != value))
				{
					this.OnContactItemTypeChanging(value);
					this.SendPropertyChanging();
					this._ContactItemType = value;
					this.SendPropertyChanged("ContactItemType");
					this.OnContactItemTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactItemValue", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string ContactItemValue
		{
			get
			{
				return this._ContactItemValue;
			}
			set
			{
				if ((this._ContactItemValue != value))
				{
					this.OnContactItemValueChanging(value);
					this.SendPropertyChanging();
					this._ContactItemValue = value;
					this.SendPropertyChanged("ContactItemValue");
					this.OnContactItemValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DocumentFolders")]
	public partial class DocumentFolder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _INSERT_TIMESTAMP;
		
		private string _INSERT_USER;
		
		private bool _IsActive;
		
		private int _CustomerID;
		
		private System.Nullable<int> _ParentID;
		
		private string _FolderName;
		
		private bool _IsStarred;
		
		private bool _IsHidden;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnINSERT_TIMESTAMPChanging(System.DateTime value);
    partial void OnINSERT_TIMESTAMPChanged();
    partial void OnINSERT_USERChanging(string value);
    partial void OnINSERT_USERChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnCustomerIDChanging(int value);
    partial void OnCustomerIDChanged();
    partial void OnParentIDChanging(System.Nullable<int> value);
    partial void OnParentIDChanged();
    partial void OnFolderNameChanging(string value);
    partial void OnFolderNameChanged();
    partial void OnIsStarredChanging(bool value);
    partial void OnIsStarredChanged();
    partial void OnIsHiddenChanging(bool value);
    partial void OnIsHiddenChanged();
    #endregion
		
		public DocumentFolder()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSERT_TIMESTAMP", DbType="DateTime NOT NULL")]
		public System.DateTime INSERT_TIMESTAMP
		{
			get
			{
				return this._INSERT_TIMESTAMP;
			}
			set
			{
				if ((this._INSERT_TIMESTAMP != value))
				{
					this.OnINSERT_TIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._INSERT_TIMESTAMP = value;
					this.SendPropertyChanged("INSERT_TIMESTAMP");
					this.OnINSERT_TIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSERT_USER", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string INSERT_USER
		{
			get
			{
				return this._INSERT_USER;
			}
			set
			{
				if ((this._INSERT_USER != value))
				{
					this.OnINSERT_USERChanging(value);
					this.SendPropertyChanging();
					this._INSERT_USER = value;
					this.SendPropertyChanged("INSERT_USER");
					this.OnINSERT_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int NOT NULL")]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
		public System.Nullable<int> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this.OnParentIDChanging(value);
					this.SendPropertyChanging();
					this._ParentID = value;
					this.SendPropertyChanged("ParentID");
					this.OnParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderName", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string FolderName
		{
			get
			{
				return this._FolderName;
			}
			set
			{
				if ((this._FolderName != value))
				{
					this.OnFolderNameChanging(value);
					this.SendPropertyChanging();
					this._FolderName = value;
					this.SendPropertyChanged("FolderName");
					this.OnFolderNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsStarred", DbType="Bit NOT NULL")]
		public bool IsStarred
		{
			get
			{
				return this._IsStarred;
			}
			set
			{
				if ((this._IsStarred != value))
				{
					this.OnIsStarredChanging(value);
					this.SendPropertyChanging();
					this._IsStarred = value;
					this.SendPropertyChanged("IsStarred");
					this.OnIsStarredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHidden", DbType="Bit NOT NULL")]
		public bool IsHidden
		{
			get
			{
				return this._IsHidden;
			}
			set
			{
				if ((this._IsHidden != value))
				{
					this.OnIsHiddenChanging(value);
					this.SendPropertyChanging();
					this._IsHidden = value;
					this.SendPropertyChanged("IsHidden");
					this.OnIsHiddenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DocumentData")]
	public partial class DocumentData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _INSERT_TIMESTAMP;
		
		private string _INSERT_USER;
		
		private bool _IsActive;
		
		private int _DocumentID;
		
		private System.Data.Linq.Binary _RawData;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnINSERT_TIMESTAMPChanging(System.DateTime value);
    partial void OnINSERT_TIMESTAMPChanged();
    partial void OnINSERT_USERChanging(string value);
    partial void OnINSERT_USERChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnDocumentIDChanging(int value);
    partial void OnDocumentIDChanged();
    partial void OnRawDataChanging(System.Data.Linq.Binary value);
    partial void OnRawDataChanged();
    #endregion
		
		public DocumentData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSERT_TIMESTAMP", DbType="DateTime NOT NULL")]
		public System.DateTime INSERT_TIMESTAMP
		{
			get
			{
				return this._INSERT_TIMESTAMP;
			}
			set
			{
				if ((this._INSERT_TIMESTAMP != value))
				{
					this.OnINSERT_TIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._INSERT_TIMESTAMP = value;
					this.SendPropertyChanged("INSERT_TIMESTAMP");
					this.OnINSERT_TIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSERT_USER", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string INSERT_USER
		{
			get
			{
				return this._INSERT_USER;
			}
			set
			{
				if ((this._INSERT_USER != value))
				{
					this.OnINSERT_USERChanging(value);
					this.SendPropertyChanging();
					this._INSERT_USER = value;
					this.SendPropertyChanged("INSERT_USER");
					this.OnINSERT_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentID", DbType="Int NOT NULL")]
		public int DocumentID
		{
			get
			{
				return this._DocumentID;
			}
			set
			{
				if ((this._DocumentID != value))
				{
					this.OnDocumentIDChanging(value);
					this.SendPropertyChanging();
					this._DocumentID = value;
					this.SendPropertyChanged("DocumentID");
					this.OnDocumentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RawData", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary RawData
		{
			get
			{
				return this._RawData;
			}
			set
			{
				if ((this._RawData != value))
				{
					this.OnRawDataChanging(value);
					this.SendPropertyChanging();
					this._RawData = value;
					this.SendPropertyChanged("RawData");
					this.OnRawDataChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EventLog")]
	public partial class EventLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _LOG_TIMESTAMP;
		
		private string _LOG_USER;
		
		private string _EventType;
		
		private string _EventMessage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLOG_TIMESTAMPChanging(System.DateTime value);
    partial void OnLOG_TIMESTAMPChanged();
    partial void OnLOG_USERChanging(string value);
    partial void OnLOG_USERChanged();
    partial void OnEventTypeChanging(string value);
    partial void OnEventTypeChanged();
    partial void OnEventMessageChanging(string value);
    partial void OnEventMessageChanged();
    #endregion
		
		public EventLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOG_TIMESTAMP", DbType="DateTime NOT NULL")]
		public System.DateTime LOG_TIMESTAMP
		{
			get
			{
				return this._LOG_TIMESTAMP;
			}
			set
			{
				if ((this._LOG_TIMESTAMP != value))
				{
					this.OnLOG_TIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._LOG_TIMESTAMP = value;
					this.SendPropertyChanged("LOG_TIMESTAMP");
					this.OnLOG_TIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOG_USER", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string LOG_USER
		{
			get
			{
				return this._LOG_USER;
			}
			set
			{
				if ((this._LOG_USER != value))
				{
					this.OnLOG_USERChanging(value);
					this.SendPropertyChanging();
					this._LOG_USER = value;
					this.SendPropertyChanged("LOG_USER");
					this.OnLOG_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventType", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string EventType
		{
			get
			{
				return this._EventType;
			}
			set
			{
				if ((this._EventType != value))
				{
					this.OnEventTypeChanging(value);
					this.SendPropertyChanging();
					this._EventType = value;
					this.SendPropertyChanged("EventType");
					this.OnEventTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventMessage", DbType="NVarChar(1000)")]
		public string EventMessage
		{
			get
			{
				return this._EventMessage;
			}
			set
			{
				if ((this._EventMessage != value))
				{
					this.OnEventMessageChanging(value);
					this.SendPropertyChanging();
					this._EventMessage = value;
					this.SendPropertyChanged("EventMessage");
					this.OnEventMessageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Documents")]
	public partial class Document : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _INSERT_TIMESTAMP;
		
		private string _INSERT_USER;
		
		private bool _IsActive;
		
		private int _CustomerID;
		
		private System.Nullable<int> _DocumentFolderID;
		
		private string _DocumentFileName;
		
		private string _DocumentType;
		
		private string _FileType;
		
		private System.Nullable<System.DateTime> _FileTimestamp;
		
		private System.Nullable<System.DateTime> _UploadDate;
		
		private System.Nullable<System.DateTime> _ExpirationDate;
		
		private string _Comments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnINSERT_TIMESTAMPChanging(System.DateTime value);
    partial void OnINSERT_TIMESTAMPChanged();
    partial void OnINSERT_USERChanging(string value);
    partial void OnINSERT_USERChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnCustomerIDChanging(int value);
    partial void OnCustomerIDChanged();
    partial void OnDocumentFolderIDChanging(System.Nullable<int> value);
    partial void OnDocumentFolderIDChanged();
    partial void OnDocumentFileNameChanging(string value);
    partial void OnDocumentFileNameChanged();
    partial void OnDocumentTypeChanging(string value);
    partial void OnDocumentTypeChanged();
    partial void OnFileTypeChanging(string value);
    partial void OnFileTypeChanged();
    partial void OnFileTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnFileTimestampChanged();
    partial void OnUploadDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUploadDateChanged();
    partial void OnExpirationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpirationDateChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    #endregion
		
		public Document()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSERT_TIMESTAMP", DbType="DateTime NOT NULL")]
		public System.DateTime INSERT_TIMESTAMP
		{
			get
			{
				return this._INSERT_TIMESTAMP;
			}
			set
			{
				if ((this._INSERT_TIMESTAMP != value))
				{
					this.OnINSERT_TIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._INSERT_TIMESTAMP = value;
					this.SendPropertyChanged("INSERT_TIMESTAMP");
					this.OnINSERT_TIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSERT_USER", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string INSERT_USER
		{
			get
			{
				return this._INSERT_USER;
			}
			set
			{
				if ((this._INSERT_USER != value))
				{
					this.OnINSERT_USERChanging(value);
					this.SendPropertyChanging();
					this._INSERT_USER = value;
					this.SendPropertyChanged("INSERT_USER");
					this.OnINSERT_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int NOT NULL")]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentFolderID", DbType="Int")]
		public System.Nullable<int> DocumentFolderID
		{
			get
			{
				return this._DocumentFolderID;
			}
			set
			{
				if ((this._DocumentFolderID != value))
				{
					this.OnDocumentFolderIDChanging(value);
					this.SendPropertyChanging();
					this._DocumentFolderID = value;
					this.SendPropertyChanged("DocumentFolderID");
					this.OnDocumentFolderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentFileName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DocumentFileName
		{
			get
			{
				return this._DocumentFileName;
			}
			set
			{
				if ((this._DocumentFileName != value))
				{
					this.OnDocumentFileNameChanging(value);
					this.SendPropertyChanging();
					this._DocumentFileName = value;
					this.SendPropertyChanged("DocumentFileName");
					this.OnDocumentFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentType", DbType="NVarChar(100)")]
		public string DocumentType
		{
			get
			{
				return this._DocumentType;
			}
			set
			{
				if ((this._DocumentType != value))
				{
					this.OnDocumentTypeChanging(value);
					this.SendPropertyChanging();
					this._DocumentType = value;
					this.SendPropertyChanged("DocumentType");
					this.OnDocumentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileType", DbType="NVarChar(100)")]
		public string FileType
		{
			get
			{
				return this._FileType;
			}
			set
			{
				if ((this._FileType != value))
				{
					this.OnFileTypeChanging(value);
					this.SendPropertyChanging();
					this._FileType = value;
					this.SendPropertyChanged("FileType");
					this.OnFileTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> FileTimestamp
		{
			get
			{
				return this._FileTimestamp;
			}
			set
			{
				if ((this._FileTimestamp != value))
				{
					this.OnFileTimestampChanging(value);
					this.SendPropertyChanging();
					this._FileTimestamp = value;
					this.SendPropertyChanged("FileTimestamp");
					this.OnFileTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadDate", DbType="Date")]
		public System.Nullable<System.DateTime> UploadDate
		{
			get
			{
				return this._UploadDate;
			}
			set
			{
				if ((this._UploadDate != value))
				{
					this.OnUploadDateChanging(value);
					this.SendPropertyChanging();
					this._UploadDate = value;
					this.SendPropertyChanged("UploadDate");
					this.OnUploadDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpirationDate", DbType="Date")]
		public System.Nullable<System.DateTime> ExpirationDate
		{
			get
			{
				return this._ExpirationDate;
			}
			set
			{
				if ((this._ExpirationDate != value))
				{
					this.OnExpirationDateChanging(value);
					this.SendPropertyChanging();
					this._ExpirationDate = value;
					this.SendPropertyChanged("ExpirationDate");
					this.OnExpirationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="NVarChar(1000)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DocumentActivityLog")]
	public partial class DocumentActivityLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _LOG_TIMESTAMP;
		
		private string _LOG_USER;
		
		private string _EventType;
		
		private string _CustomerName;
		
		private string _DocumentFileName;
		
		private string _FolderName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLOG_TIMESTAMPChanging(System.DateTime value);
    partial void OnLOG_TIMESTAMPChanged();
    partial void OnLOG_USERChanging(string value);
    partial void OnLOG_USERChanged();
    partial void OnEventTypeChanging(string value);
    partial void OnEventTypeChanged();
    partial void OnCustomerNameChanging(string value);
    partial void OnCustomerNameChanged();
    partial void OnDocumentFileNameChanging(string value);
    partial void OnDocumentFileNameChanged();
    partial void OnFolderNameChanging(string value);
    partial void OnFolderNameChanged();
    #endregion
		
		public DocumentActivityLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOG_TIMESTAMP", DbType="DateTime NOT NULL")]
		public System.DateTime LOG_TIMESTAMP
		{
			get
			{
				return this._LOG_TIMESTAMP;
			}
			set
			{
				if ((this._LOG_TIMESTAMP != value))
				{
					this.OnLOG_TIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._LOG_TIMESTAMP = value;
					this.SendPropertyChanged("LOG_TIMESTAMP");
					this.OnLOG_TIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOG_USER", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string LOG_USER
		{
			get
			{
				return this._LOG_USER;
			}
			set
			{
				if ((this._LOG_USER != value))
				{
					this.OnLOG_USERChanging(value);
					this.SendPropertyChanging();
					this._LOG_USER = value;
					this.SendPropertyChanged("LOG_USER");
					this.OnLOG_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventType", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string EventType
		{
			get
			{
				return this._EventType;
			}
			set
			{
				if ((this._EventType != value))
				{
					this.OnEventTypeChanging(value);
					this.SendPropertyChanging();
					this._EventType = value;
					this.SendPropertyChanged("EventType");
					this.OnEventTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="NVarChar(1000)")]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this.OnCustomerNameChanging(value);
					this.SendPropertyChanging();
					this._CustomerName = value;
					this.SendPropertyChanged("CustomerName");
					this.OnCustomerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentFileName", DbType="NVarChar(1000)")]
		public string DocumentFileName
		{
			get
			{
				return this._DocumentFileName;
			}
			set
			{
				if ((this._DocumentFileName != value))
				{
					this.OnDocumentFileNameChanging(value);
					this.SendPropertyChanging();
					this._DocumentFileName = value;
					this.SendPropertyChanged("DocumentFileName");
					this.OnDocumentFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderName", DbType="NVarChar(1000)")]
		public string FolderName
		{
			get
			{
				return this._FolderName;
			}
			set
			{
				if ((this._FolderName != value))
				{
					this.OnFolderNameChanging(value);
					this.SendPropertyChanging();
					this._FolderName = value;
					this.SendPropertyChanged("FolderName");
					this.OnFolderNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class fn_GetDocumentFoldersForCustomerResult
	{
		
		private int _ID;
		
		private System.DateTime _INSERT_TIMESTAMP;
		
		private string _INSERT_USER;
		
		private bool _IsActive;
		
		private int _CustomerID;
		
		private System.Nullable<int> _ParentID;
		
		private string _FolderName;
		
		private bool _IsStarred;
		
		private bool _IsHidden;
		
		public fn_GetDocumentFoldersForCustomerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSERT_TIMESTAMP", DbType="DateTime NOT NULL")]
		public System.DateTime INSERT_TIMESTAMP
		{
			get
			{
				return this._INSERT_TIMESTAMP;
			}
			set
			{
				if ((this._INSERT_TIMESTAMP != value))
				{
					this._INSERT_TIMESTAMP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSERT_USER", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string INSERT_USER
		{
			get
			{
				return this._INSERT_USER;
			}
			set
			{
				if ((this._INSERT_USER != value))
				{
					this._INSERT_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int NOT NULL")]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this._CustomerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
		public System.Nullable<int> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderName", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string FolderName
		{
			get
			{
				return this._FolderName;
			}
			set
			{
				if ((this._FolderName != value))
				{
					this._FolderName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsStarred", DbType="Bit NOT NULL")]
		public bool IsStarred
		{
			get
			{
				return this._IsStarred;
			}
			set
			{
				if ((this._IsStarred != value))
				{
					this._IsStarred = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHidden", DbType="Bit NOT NULL")]
		public bool IsHidden
		{
			get
			{
				return this._IsHidden;
			}
			set
			{
				if ((this._IsHidden != value))
				{
					this._IsHidden = value;
				}
			}
		}
	}
	
	public partial class fn_GetAllFolderNamesResult
	{
		
		private string _FolderName;
		
		public fn_GetAllFolderNamesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderName", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string FolderName
		{
			get
			{
				return this._FolderName;
			}
			set
			{
				if ((this._FolderName != value))
				{
					this._FolderName = value;
				}
			}
		}
	}
	
	public partial class fn_GetDocumentsForCustomerResult
	{
		
		private int _ID;
		
		private bool _IsActive;
		
		private int _CustomerID;
		
		private System.Nullable<int> _DocumentFolderID;
		
		private string _DocumentFileName;
		
		private string _DocumentType;
		
		private string _FileType;
		
		private System.Nullable<System.DateTime> _FileTimestamp;
		
		private System.Nullable<System.DateTime> _UploadDate;
		
		private System.Nullable<System.DateTime> _ExpirationDate;
		
		private string _Comments;
		
		public fn_GetDocumentsForCustomerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int NOT NULL")]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this._CustomerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentFolderID", DbType="Int")]
		public System.Nullable<int> DocumentFolderID
		{
			get
			{
				return this._DocumentFolderID;
			}
			set
			{
				if ((this._DocumentFolderID != value))
				{
					this._DocumentFolderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentFileName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DocumentFileName
		{
			get
			{
				return this._DocumentFileName;
			}
			set
			{
				if ((this._DocumentFileName != value))
				{
					this._DocumentFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentType", DbType="NVarChar(100)")]
		public string DocumentType
		{
			get
			{
				return this._DocumentType;
			}
			set
			{
				if ((this._DocumentType != value))
				{
					this._DocumentType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileType", DbType="NVarChar(100)")]
		public string FileType
		{
			get
			{
				return this._FileType;
			}
			set
			{
				if ((this._FileType != value))
				{
					this._FileType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileTimestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> FileTimestamp
		{
			get
			{
				return this._FileTimestamp;
			}
			set
			{
				if ((this._FileTimestamp != value))
				{
					this._FileTimestamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadDate", DbType="Date")]
		public System.Nullable<System.DateTime> UploadDate
		{
			get
			{
				return this._UploadDate;
			}
			set
			{
				if ((this._UploadDate != value))
				{
					this._UploadDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpirationDate", DbType="Date")]
		public System.Nullable<System.DateTime> ExpirationDate
		{
			get
			{
				return this._ExpirationDate;
			}
			set
			{
				if ((this._ExpirationDate != value))
				{
					this._ExpirationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="NVarChar(1000)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this._Comments = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
